# This script should be used to delete a single lettered drive
# Please specify the drive letter and disk number of the drive properly to
# ensure proper functioning
---
- hosts: localhost
  gather_facts: no
  
  tasks:

    - name: Fetch Tasks from FreshService
      shell: |
        source ../secret.env
        python ../scripts/main.py
      delegate_to: localhost

    - name: Fetch Tasks from FreshService
      script: ../scripts/main.py
      args:
        chdir: /mnt/c/Users/'Mervin Hemaraju'/'My Files'/Projects/'Multi Platform'/disk_removal_automation
      delegate_to: localhost

    - include_vars:
        file: data.json
        name: varjs

    - name: Delete partition
      community.windows.win_partition:
        drive_letter: "{{ varjs.drive }}"
        state: absent

    - name: Put Disk Offline
      win_shell: Set-Disk -Number {{ varjs.disk }} -IsOffline $True
      





        