---
- hosts: win_jump_01
  gather_facts: no
  
  tasks:
    - name: Fetch Tasks from FreshService
      shell: |
        python /home/ubuntu/projects/disk-removal-automation/scripts/get_tasks.py
      delegate_to: localhost
      environment:
        ENV_FRESH_SERVICE_KEY_API_B64: ""
        ENV_FRESH_SERVICE_URL: https://checkoutsupport.freshservice.com/api/v2

    - name: Get Active Username
      become: false
      local_action: command whoami
      register: username_on_the_host

    #- debug: var=username_on_the_host

    - include_vars:
        file: "/home/{{ username_on_the_host.stdout }}/.diskremconf.json"
        name: varjs

    #- debug: var=varjs.drive

    - name: Delete partition on Windows Server
      win_partition:
        drive_letter: "{{ item.drive }}"
        state: absent
      with_items: "{{ varjs.drives }}"

    - name: Put Disk Offline on Windows Server
      win_shell: Set-Disk -Number {{ item.disk }} -IsOffline $True
      with_items: "{{ varjs.drives }}"
      when: item.offline == 1
      





        